# Generated by Django 4.0 on 2021-12-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
